-- ============================================================
-- 004_2026_school_data.sql
-- Adds 63 new schools (HCM + KV2 Bình Dương + KV3 BRVT),
-- their NORMAL programs, and 2026 NV1 cutoff scores for
-- all 170 schools in the 2026 admissions list.
--
-- Depends on: 003_make_address_nullable.sql
-- Safe to re-run: uses WHERE NOT EXISTS + ON CONFLICT
-- ============================================================


-- ── PART 1: Insert new schools ───────────────────────────────────────
INSERT INTO schools (name, type, district, latitude, longitude)
SELECT v.name, v.type, v.district, v.lat, v.lng
FROM (VALUES
  ('Trường Trung học Thực hành ĐHSP', 'PUBLIC', 'Quận 5', NULL, NULL),
  ('Dự án THPT Phường Đông Hưng Thuận', 'PUBLIC', 'Quận 12', 10.8431, 106.6259),
  ('Dự án Tiểu học, THCS và THPT Phường Thới An', 'PUBLIC', 'Quận 12', 10.8684, 106.6522),
  ('Dự án THPT Phường Tân Phú', 'PUBLIC', 'Quận Tân Phú', NULL, NULL),
  ('THPT Vĩnh Lộc', 'PUBLIC', 'Quận Bình Tân', 10.8099, 106.5921),
  ('THPT Lý Thái Tổ KV2', 'PUBLIC', 'Thuận An', 10.9632, 106.729),
  ('THPT Lê Lợi KV2', 'PUBLIC', 'Bình Dương', NULL, NULL),
  ('THPT Tân Bình Bình Dương KV2', 'PUBLIC', 'Bắc Tân Uyên', 11.1833, 106.7279),
  ('THPT Dĩ An KV2', 'PUBLIC', 'Dĩ An', NULL, NULL),
  ('THPT Võ Minh Đức KV2', 'PUBLIC', 'Bình Dương', NULL, NULL),
  ('THCS THPT Minh Hòa KV2', 'PUBLIC', 'Dầu Tiếng', NULL, NULL),
  ('THPT Bình An KV2', 'PUBLIC', 'Dĩ An', 10.9014, 106.8068),
  ('THPT Nguyễn Đình Chiểu KV2', 'PUBLIC', 'Thủ Dầu Một', 10.9999, 106.6471),
  ('THPT Trịnh Hoài Đức KV2', 'PUBLIC', 'Thủ Dầu Một', NULL, NULL),
  ('THPT Nguyễn Trãi Bình Dương KV2', 'PUBLIC', 'Thuận An', NULL, NULL),
  ('THPT Nguyễn An Ninh Bình Dương KV2', 'PUBLIC', 'Dĩ An', 10.8751, 106.7544),
  ('THPT Huỳnh Văn Nghệ KV2', 'PUBLIC', 'Bình Dương', NULL, NULL),
  ('THPT Phước Vĩnh KV2', 'PUBLIC', 'Phú Giáo', NULL, NULL),
  ('THPT Bến Cát KV2', 'PUBLIC', 'Bến Cát', NULL, NULL),
  ('THPT Dầu Tiếng KV2', 'PUBLIC', 'Dầu Tiếng', 11.2818, 106.3668),
  ('THPT Bình Phú Bình Dương KV2', 'PUBLIC', 'Bình Dương', NULL, NULL),
  ('THPT Trần Văn Ơn KV2', 'PUBLIC', 'Dĩ An', NULL, NULL),
  ('THCS và THPT Tây Sơn KV2', 'PUBLIC', 'Bình Dương', NULL, NULL),
  ('THCS và THPT Nguyễn Huệ KV2', 'PUBLIC', 'Dầu Tiếng', NULL, NULL),
  ('THPT Tây Nam KV2', 'PUBLIC', 'Bình Dương', NULL, NULL),
  ('THPT Tân Phước Khánh KV2', 'PUBLIC', 'Tân Uyên', 11.0037, 106.7221),
  ('THPT Thái Hòa KV2', 'PUBLIC', 'Tân Uyên', NULL, NULL),
  ('THPT An Mỹ KV2', 'PUBLIC', 'Bình Dương', 11.0162, 106.682),
  ('THPT Phước Hòa KV2', 'PUBLIC', 'Phú Giáo', NULL, NULL),
  ('THPT Bàu Bàng KV2', 'PUBLIC', 'Bàu Bàng', NULL, NULL),
  ('THPT Long Hòa KV2', 'PUBLIC', 'Bình Dương', NULL, NULL),
  ('THPT Nguyễn Thị Minh Khai Bình Dương KV2', 'PUBLIC', 'Bình Dương', NULL, NULL),
  ('THPT Thường Tân KV2', 'PUBLIC', 'Bắc Tân Uyên', NULL, NULL),
  ('THPT Thanh Tuyền KV2', 'PUBLIC', 'Dầu Tiếng', NULL, NULL),
  ('Dự án THPT Phường Dĩ An KV2', 'PUBLIC', 'Dĩ An', 10.9039, 106.768),
  ('THPT Vũng Tàu KV3', 'PUBLIC', 'Vũng Tàu', NULL, NULL),
  ('THPT Châu Thành KV3', 'PUBLIC', 'Châu Đức', NULL, NULL),
  ('THPT Trần Phú BRVT KV3', 'PUBLIC', 'Vũng Tàu', NULL, NULL),
  ('THPT Xuyên Mộc KV3', 'PUBLIC', 'Xuyên Mộc', NULL, NULL),
  ('THPT Phú Mỹ KV3', 'PUBLIC', 'Phú Mỹ', NULL, NULL),
  ('THPT Trần Hưng Đạo BRVT KV3', 'PUBLIC', 'Bà Rịa', NULL, NULL),
  ('THPT Hắc Dịch KV3', 'PUBLIC', 'Phú Mỹ', NULL, NULL),
  ('THPT Trần Văn Quan KV3', 'PUBLIC', 'Bà Rịa - Vũng Tàu', NULL, NULL),
  ('THPT Võ Thị Sáu BRVT KV3', 'PUBLIC', 'Bà Rịa', NULL, NULL),
  ('THPT Hòa Hội KV3', 'PUBLIC', 'Châu Đức', NULL, NULL),
  ('THPT Nguyễn Bỉnh Khiêm KV3', 'PUBLIC', 'Xuyên Mộc', NULL, NULL),
  ('THPT Nguyễn Trãi BRVT KV3', 'PUBLIC', 'Bà Rịa', NULL, NULL),
  ('THPT Phước Bửu KV3', 'PUBLIC', 'Xuyên Mộc', NULL, NULL),
  ('THPT Long Hải Phước Tỉnh KV3', 'PUBLIC', 'Long Điền', NULL, NULL),
  ('THPT Nguyễn Văn Cừ BRVT KV3', 'PUBLIC', 'Bà Rịa - Vũng Tàu', NULL, NULL),
  ('THPT Minh Đạm KV3', 'PUBLIC', 'Long Điền', NULL, NULL),
  ('THPT Nguyễn Khuyến BRVT KV3', 'PUBLIC', 'Bà Rịa - Vũng Tàu', NULL, NULL),
  ('THPT Nguyễn Huệ BRVT KV3', 'PUBLIC', 'Bà Rịa - Vũng Tàu', NULL, NULL),
  ('THPT Đinh Tiên Hoàng KV3', 'PUBLIC', 'Bà Rịa - Vũng Tàu', NULL, NULL),
  ('THPT Trần Nguyên Hãn KV3', 'PUBLIC', 'Bà Rịa - Vũng Tàu', NULL, NULL),
  ('THPT Ngô Quyền KV3', 'PUBLIC', 'Bà Rịa - Vũng Tàu', NULL, NULL),
  ('THPT Hòa Bình KV3', 'PUBLIC', 'Bà Rịa - Vũng Tàu', NULL, NULL),
  ('THPT Trần Quang Khải BRVT KV3', 'PUBLIC', 'Bà Rịa - Vũng Tàu', NULL, NULL),
  ('THPT Dương Bạch Mai KV3', 'PUBLIC', 'Bà Rịa - Vũng Tàu', NULL, NULL),
  ('THPT Bà Rịa KV3', 'PUBLIC', 'Bà Rịa', NULL, NULL),
  ('THPT Bưng Riềng KV3', 'PUBLIC', 'Xuyên Mộc', NULL, NULL),
  ('THPT Nguyễn Du BRVT KV3', 'PUBLIC', 'Bà Rịa - Vũng Tàu', NULL, NULL),
  ('Dự án THPT Phường Phú Mỹ KV3', 'PUBLIC', 'Phú Mỹ', NULL, NULL)
) AS v(name, type, district, lat, lng)
WHERE NOT EXISTS (SELECT 1 FROM schools s WHERE s.name = v.name);


-- ── PART 2: Insert NORMAL program for each new school ────────────────
INSERT INTO programs (school_id, name, type)
SELECT s.id, 'Thường', 'NORMAL'
FROM schools s
WHERE s.name IN (
  'Trường Trung học Thực hành ĐHSP',
  'Dự án THPT Phường Đông Hưng Thuận',
  'Dự án Tiểu học, THCS và THPT Phường Thới An',
  'Dự án THPT Phường Tân Phú',
  'THPT Vĩnh Lộc',
  'THPT Lý Thái Tổ KV2',
  'THPT Lê Lợi KV2',
  'THPT Tân Bình Bình Dương KV2',
  'THPT Dĩ An KV2',
  'THPT Võ Minh Đức KV2',
  'THCS THPT Minh Hòa KV2',
  'THPT Bình An KV2',
  'THPT Nguyễn Đình Chiểu KV2',
  'THPT Trịnh Hoài Đức KV2',
  'THPT Nguyễn Trãi Bình Dương KV2',
  'THPT Nguyễn An Ninh Bình Dương KV2',
  'THPT Huỳnh Văn Nghệ KV2',
  'THPT Phước Vĩnh KV2',
  'THPT Bến Cát KV2',
  'THPT Dầu Tiếng KV2',
  'THPT Bình Phú Bình Dương KV2',
  'THPT Trần Văn Ơn KV2',
  'THCS và THPT Tây Sơn KV2',
  'THCS và THPT Nguyễn Huệ KV2',
  'THPT Tây Nam KV2',
  'THPT Tân Phước Khánh KV2',
  'THPT Thái Hòa KV2',
  'THPT An Mỹ KV2',
  'THPT Phước Hòa KV2',
  'THPT Bàu Bàng KV2',
  'THPT Long Hòa KV2',
  'THPT Nguyễn Thị Minh Khai Bình Dương KV2',
  'THPT Thường Tân KV2',
  'THPT Thanh Tuyền KV2',
  'Dự án THPT Phường Dĩ An KV2',
  'THPT Vũng Tàu KV3',
  'THPT Châu Thành KV3',
  'THPT Trần Phú BRVT KV3',
  'THPT Xuyên Mộc KV3',
  'THPT Phú Mỹ KV3',
  'THPT Trần Hưng Đạo BRVT KV3',
  'THPT Hắc Dịch KV3',
  'THPT Trần Văn Quan KV3',
  'THPT Võ Thị Sáu BRVT KV3',
  'THPT Hòa Hội KV3',
  'THPT Nguyễn Bỉnh Khiêm KV3',
  'THPT Nguyễn Trãi BRVT KV3',
  'THPT Phước Bửu KV3',
  'THPT Long Hải Phước Tỉnh KV3',
  'THPT Nguyễn Văn Cừ BRVT KV3',
  'THPT Minh Đạm KV3',
  'THPT Nguyễn Khuyến BRVT KV3',
  'THPT Nguyễn Huệ BRVT KV3',
  'THPT Đinh Tiên Hoàng KV3',
  'THPT Trần Nguyên Hãn KV3',
  'THPT Ngô Quyền KV3',
  'THPT Hòa Bình KV3',
  'THPT Trần Quang Khải BRVT KV3',
  'THPT Dương Bạch Mai KV3',
  'THPT Bà Rịa KV3',
  'THPT Bưng Riềng KV3',
  'THPT Nguyễn Du BRVT KV3',
  'Dự án THPT Phường Phú Mỹ KV3'
)
AND NOT EXISTS (
  SELECT 1 FROM programs p WHERE p.school_id = s.id AND p.type = 'NORMAL'
);


-- ── PART 3: Insert 2026 NV1 cutoff scores (170 schools) ──────────────
-- Uses ON CONFLICT DO UPDATE so this is safe to re-run
WITH school_scores(school_name, score) AS (
  VALUES
  ('THPT Trưng Vương', 21.75),
  ('THPT Bùi Thị Xuân', 24.25),
  ('THPT Ten Lơ Man', 20.5),
  ('THPT Năng khiếu TDTT', 14.0),
  ('THCS-THPT Trần Đại Nghĩa', 24.0),
  ('THPT Lương Thế Vinh', 22.75),
  ('THPT Giồng Ông Tố', 18.75),
  ('THPT Thủ Thiêm', 14.25),
  ('THPT Lê Quý Đôn', 23.75),
  ('THPT Nguyễn Thị Minh Khai', 24.5),
  ('THPT Lê Thị Hồng Gấm', 14.25),
  ('THPT Marie Curie', 22.25),
  ('THPT Nguyễn Thị Diệu', 15.75),
  ('THPT Nguyễn Trãi', 15.25),
  ('THPT Nguyễn Hữu Thọ', 18.25),
  ('Trường Trung học Thực hành Sài Gòn', 23.5),
  ('THPT Hùng Vương', 21.0),
  ('Trường Trung học Thực hành ĐHSP', 24.5),
  ('THPT Trần Khai Nguyên', 23.0),
  ('THPT Trần Hữu Trang', 14.0),
  ('THPT Mạc Đĩnh Chi', 24.25),
  ('THPT Bình Phú', 22.5),
  ('THPT Nguyễn Tất Thành', 19.75),
  ('THPT Phạm Phú Thứ', 17.0),
  ('THPT Lê Thánh Tôn', 20.0),
  ('THPT Tân Phong', 15.75),
  ('THPT Ngô Quyền', 21.25),
  ('THPT Nam Sài Gòn', 22.25),
  ('THPT Lương Văn Can', 15.75),
  ('THPT Ngô Gia Tự', 13.25),
  ('THPT Tạ Quang Bửu', 18.0),
  ('THPT Nguyễn Văn Linh', 11.75),
  ('THPT Võ Văn Kiệt', 18.0),
  ('THPT Chuyên Năng khiếu TDTT Nguyễn Thị Định', 14.5),
  ('THPT Nguyễn Huệ', 18.5),
  ('THPT Phước Long', 19.25),
  ('THPT Long Trường', 12.5),
  ('THPT Nguyễn Văn Tăng', 12.0),
  ('THPT Dương Văn Thì', 16.5),
  ('THPT Nguyễn Khuyến', 20.75),
  ('THPT Nguyễn Du', 21.75),
  ('THPT Nguyễn An Ninh', 16.25),
  ('THCS-THPT Diên Hồng', 15.0),
  ('THCS-THPT Sương Nguyệt Anh', 13.5),
  ('THPT Nguyễn Hiền', 19.75),
  ('THPT Trần Quang Khải', 17.75),
  ('THPT Nam Kỳ Khởi Nghĩa', 16.5),
  ('THPT Võ Trường Toản', 22.5),
  ('THPT Trường Chinh', 19.25),
  ('Dự án THPT Phường Đông Hưng Thuận', 16.0),
  ('Dự án Tiểu học, THCS và THPT Phường Thới An', 16.25),
  ('THPT Thạnh Lộc', 17.5),
  ('THPT Thanh Đa', 16.25),
  ('THPT Võ Thị Sáu', 21.0),
  ('THPT Gia Định', 23.5),
  ('THPT Phan Đăng Lưu', 17.5),
  ('THPT Trần Văn Giàu', 18.0),
  ('THPT Hoàng Hoa Thám', 20.75),
  ('THPT Gò Vấp', 18.0),
  ('THPT Nguyễn Công Trứ', 22.0),
  ('THPT Trần Hưng Đạo', 22.25),
  ('THPT Nguyễn Trung Trực', 19.75),
  ('THPT Phú Nhuận', 24.0),
  ('THPT Hàn Thuyên', 16.25),
  ('THPT Tân Bình', 21.5),
  ('THPT Nguyễn Chí Thanh', 20.25),
  ('THPT Trần Phú', 24.25),
  ('THPT Nguyễn Thượng Hiền', 24.75),
  ('THPT Nguyễn Thái Bình', 18.75),
  ('THPT Nguyễn Hữu Huân', 24.25),
  ('THPT Thủ Đức', 22.75),
  ('THPT Tam Phú', 20.0),
  ('THPT Hiệp Bình', 16.75),
  ('THPT Đào Sơn Tây', 14.75),
  ('THPT Linh Trung', 16.25),
  ('THPT Bình Chiêu', 15.75),
  ('THPT Bình Chánh', 14.25),
  ('THPT Tân Túc', 12.75),
  ('THPT Vĩnh Lộc B', 16.25),
  ('THPT Năng khiếu TDTT Bình Chánh', 13.5),
  ('THPT Phong Phú', 10.75),
  ('THPT Lê Minh Xuân', 14.25),
  ('THPT Đa Phước', 10.5),
  ('THPT Bình Khánh', 10.0),
  ('THPT Cần Thạnh', 9.0),
  ('THPT An Nghĩa', 10.0),
  ('THPT Củ Chi', 16.0),
  ('THPT Quang Trung', 12.25),
  ('THPT An Nhơn Tây', 11.5),
  ('THPT Trung Phú', 16.25),
  ('THPT Trung Lập', 10.5),
  ('THPT Phú Hòa', 13.5),
  ('THPT Tân Thông Hội', 14.75),
  ('THPT Nguyễn Hữu Cầu', 24.0),
  ('THPT Lý Thường Kiệt', 20.75),
  ('THPT Bà Điểm', 20.5),
  ('THPT Nguyễn Văn Cừ', 15.5),
  ('THPT Nguyễn Hữu Tiến', 19.0),
  ('THPT Phạm Văn Sáng', 17.5),
  ('THPT Hồ Thị Bi', 17.25),
  ('THPT Long Thới', 13.25),
  ('THPT Phước Kiển', 11.75),
  ('THPT Dương Văn Dương', 13.25),
  ('THPT Tây Thạnh', 23.25),
  ('THPT Lê Trọng Tấn', 21.75),
  ('Dự án THPT Phường Tân Phú', 16.25),
  ('THPT Vĩnh Lộc', 19.0),
  ('THPT Nguyễn Hữu Cảnh', 21.0),
  ('THPT Bình Hưng Hòa', 19.75),
  ('THPT Bình Tân', 16.0),
  ('THPT Bình Trị Đông B (THPT Hoàng Thế Thiện)', 15.5),
  ('THPT An Lạc', 17.25),
  ('THPT Lý Thái Tổ KV2', 17.25),
  ('THPT Lê Lợi KV2', 13.25),
  ('THPT Tân Bình Bình Dương KV2', 13.5),
  ('THPT Dĩ An KV2', 23.25),
  ('THPT Võ Minh Đức KV2', 20.0),
  ('THCS THPT Minh Hòa KV2', 10.75),
  ('THPT Bình An KV2', 19.0),
  ('THPT Nguyễn Đình Chiểu KV2', 16.75),
  ('THPT Trịnh Hoài Đức KV2', 23.25),
  ('THPT Nguyễn Trãi Bình Dương KV2', 19.75),
  ('THPT Nguyễn An Ninh Bình Dương KV2', 15.75),
  ('THPT Huỳnh Văn Nghệ KV2', 15.0),
  ('THPT Phước Vĩnh KV2', 11.5),
  ('THPT Bến Cát KV2', 18.5),
  ('THPT Dầu Tiếng KV2', 12.5),
  ('THPT Bình Phú Bình Dương KV2', 15.5),
  ('THPT Trần Văn Ơn KV2', 16.75),
  ('THCS và THPT Tây Sơn KV2', 10.25),
  ('THCS và THPT Nguyễn Huệ KV2', 9.0),
  ('THPT Tây Nam KV2', 14.5),
  ('THPT Tân Phước Khánh KV2', 19.25),
  ('THPT Thái Hòa KV2', 15.5),
  ('THPT An Mỹ KV2', 18.5),
  ('THPT Phước Hòa KV2', 11.75),
  ('THPT Bàu Bàng KV2', 15.25),
  ('THPT Long Hòa KV2', 12.0),
  ('THPT Nguyễn Thị Minh Khai Bình Dương KV2', 20.25),
  ('THPT Thường Tân KV2', 12.0),
  ('THPT Thanh Tuyền KV2', 13.5),
  ('Dự án THPT Phường Dĩ An KV2', 16.5),
  ('THPT Vũng Tàu KV3', 21.75),
  ('THPT Châu Thành KV3', 18.5),
  ('THPT Trần Phú BRVT KV3', 9.0),
  ('THPT Xuyên Mộc KV3', 12.25),
  ('THPT Phú Mỹ KV3', 11.5),
  ('THPT Trần Hưng Đạo BRVT KV3', 11.5),
  ('THPT Hắc Dịch KV3', 9.0),
  ('THPT Trần Văn Quan KV3', 10.75),
  ('THPT Võ Thị Sáu BRVT KV3', 11.0),
  ('THPT Hòa Hội KV3', 10.25),
  ('THPT Nguyễn Bỉnh Khiêm KV3', 10.25),
  ('THPT Nguyễn Trãi BRVT KV3', 10.0),
  ('THPT Phước Bửu KV3', 9.0),
  ('THPT Long Hải Phước Tỉnh KV3', 10.5),
  ('THPT Nguyễn Văn Cừ BRVT KV3', 9.0),
  ('THPT Minh Đạm KV3', 11.5),
  ('THPT Nguyễn Khuyến BRVT KV3', 15.75),
  ('THPT Nguyễn Huệ BRVT KV3', 19.25),
  ('THPT Đinh Tiên Hoàng KV3', 17.25),
  ('THPT Trần Nguyên Hãn KV3', 16.5),
  ('THPT Ngô Quyền KV3', 10.0),
  ('THPT Hòa Bình KV3', 9.0),
  ('THPT Trần Quang Khải BRVT KV3', 12.75),
  ('THPT Dương Bạch Mai KV3', 9.0),
  ('THPT Bà Rịa KV3', 14.0),
  ('THPT Bưng Riềng KV3', 9.0),
  ('THPT Nguyễn Du BRVT KV3', 15.25),
  ('Dự án THPT Phường Phú Mỹ KV3', 9.0)
)
INSERT INTO cutoffs (program_id, year, cutoff_score)
SELECT p.id, 2026, ss.score
FROM school_scores ss
JOIN schools  s ON s.name  = ss.school_name
JOIN programs p ON p.school_id = s.id AND p.type = 'NORMAL'
ON CONFLICT (program_id, year)
  DO UPDATE SET cutoff_score = EXCLUDED.cutoff_score;
